imports:
    - { resource: tables.yml }

services:
    phpbb.consentmanager.service:
        class: phpbb\consentmanager\service\consent_manager
        arguments:
            - '@config'
            - '@config_text'
            - '@language'
            - '@dispatcher'
            - '@template.twig.environment'
            - '@path_helper'
            - '@filesystem'
            - '@request'

    phpbb.consentmanager.log_manager:
        class: phpbb\consentmanager\service\log_manager
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%tables.phpbb.consentmanager.consent_logs%'

    phpbb.consentmanager.acp_manager:
        class: phpbb\consentmanager\service\acp_manager
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@config_text'
            - '@language'
            - '@log'
            - '@phpbb.consentmanager.service'
            - '@text_formatter.cache'
            - '@user'
            - '%tables.phpbb.consentmanager.consent_logs%'

    phpbb.consentmanager.media_manager:
        class: phpbb\consentmanager\service\media_manager
        arguments:
            - '@phpbb.consentmanager.service'

    phpbb.consentmanager.listener:
        class: phpbb\consentmanager\event\listener
        arguments:
            - '@controller.helper'
            - '@language'
            - '@phpbb.consentmanager.service'
            - '@template'
            - '@phpbb.consentmanager.media_manager'
        tags:
            - { name: event.listener }

    phpbb.consentmanager.controller.acp:
        class: phpbb\consentmanager\controller\acp_controller
        arguments:
            - '@language'
            - '@phpbb.consentmanager.acp_manager'
            - '@request'
            - '@template'

    phpbb.consentmanager.controller.log:
        class: phpbb\consentmanager\controller\log_controller
        arguments:
            - '@phpbb.consentmanager.log_manager'
            - '@phpbb.consentmanager.service'
