name: Tests

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

jobs:
    javascript-tests:
        name: JavaScript tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install JavaScript dependencies
              run: |
                  npm ci

            - name: Run JavaScript tests
              run: |
                  npm test

    call-tests:
        name: Extension tests
        uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
        with:
            EXTNAME: phpbb/consentmanager
            CODECOV: 1
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
