name: Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    call-tests:
        name: Extension tests
        uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
        with:
            EXTNAME: phpbb/consentmanager
            RUN_MYSQL_JOBS: 0
            RUN_PGSQL_JOBS: 0
            RUN_MSSQL_JOBS: 0
            RUN_WINDOWS_JOBS: 0
